# 应用服务 WEB 访问端口
server:
  port: 8081

spring:
  application:
    name: zjc-common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.116.149.224:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: 1.116.149.224
    port: 6379
    password: zjc20000220
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.zhang.demo.entity # 别名扫描包
logging:
  level:
    com.zhang: debug

